<?php

/**
 * @file
 * Contains custom_descriptions.module
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_FORM_ID_form_alter().
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function custom_descriptions_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_article_form' || $form_id === 'node_article_edit_form') {
    $current_user_roles = \Drupal::currentUser()->getRoles();
    if (in_array('editor', $current_user_roles)) {
      $form['title']['widget'][0]['value']['#description'] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.";
    }
  }
}
